[package]
name = "xpallet-gateway-common-rpc-runtime-api"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive", "max-encoded-len"] }

# Substrate primitives
sp-api = { git = "https://github.com/btclayer2/polkadot-sdk", branch = "polkadot-v1.3.0", default-features = false }
sp-runtime = { git = "https://github.com/btclayer2/polkadot-sdk", branch = "polkadot-v1.3.0", default-features = false }
sp-std = { git = "https://github.com/btclayer2/polkadot-sdk", branch = "polkadot-v1.3.0", default-features = false }

# BEVM primitives
bevm-primitives = { path = "../../../../../primitives", default-features = false }
xp-assets-registrar = { path = "../../../../../primitives/assets-registrar", default-features = false }
xp-runtime = { path = "../../../../../primitives/runtime", default-features = false }

# BEVM pallets
xpallet-gateway-common = { path = "../../", default-features = false }
xpallet-gateway-records = { path = "../../../records", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    # Substrate primitives
    "sp-api/std",
    "sp-runtime/std",
    "sp-std/std",
    # BEVM primitives
    "bevm-primitives/std",
    "xp-assets-registrar/std",
    "xp-runtime/std",
    # BEVM pallets
    "xpallet-gateway-common/std",
    "xpallet-gateway-records/std",
]
