[package]
name = "xpallet-transaction-fee-rpc-runtime-api"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive", "max-encoded-len"] }

# Substrate primtives
sp-api = { git = "https://github.com/btclayer2/polkadot-sdk", branch = "polkadot-v1.3.0", default-features = false }
sp-runtime = { git = "https://github.com/btclayer2/polkadot-sdk", branch = "polkadot-v1.3.0", default-features = false }

# BEVM pallets
xpallet-transaction-fee = { path = "../..", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    # Substrate primtives
    "sp-api/std",
    "sp-runtime/std",
    # BEVM pallets
    "xpallet-transaction-fee/std",
]
