[package]
name = "xpallet-gateway-records-rpc-runtime-api"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true }

# Substrate primitives
sp-api = { workspace = true }
sp-std = { workspace = true }

# BEVM primitives
bevm-primitives = { path = "../../../../../primitives", default-features = false }

# BEVM pallets
xpallet-gateway-records = { path = "../../", default-features = false }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    # Substrate primitives
    "sp-api/std",
    "sp-std/std",
    # BEVM primitives
    "bevm-primitives/std",
    # BEVM pallets
    "xpallet-gateway-records/std",
]
